project_id = "fcxegeffqmhpleaipvov"
[functions.send-resend-email]
verify_jwt = false
import_map = "./functions/send-resend-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-resend-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-resend-email/*.html" ]

[functions.process-notification-queue]
verify_jwt = false
entrypoint = "./functions/process-notification-queue/index.ts"

[functions.cron-contract-reminders]
verify_jwt = false
entrypoint = "./functions/cron-contract-reminders/index.ts"
